[tools]
## https://go.dev/doc/devel/release
go = '1.26'
## https://github.com/goreleaser/goreleaser/releases
"goreleaser" = '2.17'
## https://github.com/golangci/golangci-lint/releases
"golangci-lint" = '2'
