[tools]
## https://go.dev/doc/devel/release
go = '1.26'
## https://github.com/goreleaser/goreleaser/releases
"goreleaser" = '2.17'
## https://github.com/golangci/golangci-lint/releases
"golangci-lint" = '2'
## https://github.com/securego/gosec/releases
"aqua:securego/gosec" = '2'

[tasks."build"]
run = [
    "goreleaser build --clean --snapshot --single-target"
]

[tasks."lint"]
run = [
    "golangci-lint run ./...",
    "gosec -exclude=G301,G302,G304,G306,G204,G703,G108 ./..."
]
