package mise

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/rs/zerolog/log"
	"github.com/thedataflows/dotdrift/internal/apply"
	"github.com/thedataflows/dotdrift/internal/profile"
	"github.com/thedataflows/dotdrift/internal/resolve"
)

// ToolsStep installs the plan's tools via mise and activates them globally
// by writing the resolved [tools] table into dotdrift's conf.d fragment
// (issue 0037): mise loads ~/.config/mise/conf.d/*.toml as global config, so
// installed tools resolve on PATH. config.toml itself is never touched — it
// may be a managed dotfile. A run whose plan has no tools removes a stale
// fragment (removed tools must stop resolving).
type ToolsStep struct {
	Runner     Runner
	Plan       *resolve.Plan
	ConfigPath string
	// FragmentPath is dotdrift's global activation fragment (see
	// ToolsFragmentPath). Empty skips the fragment (tests, onboard).
	FragmentPath string
}

var _ apply.Step = (*ToolsStep)(nil)

func (s *ToolsStep) Name() string { return "tools" }

func (s *ToolsStep) Run(ctx context.Context) error {
	if s.Runner == nil {
		return fmt.Errorf("no mise runner configured")
	}
	if s.Plan == nil {
		return fmt.Errorf("plan is nil")
	}
	if len(s.Plan.Tools.Versions) == 0 {
		if s.FragmentPath != "" {
			if err := os.Remove(s.FragmentPath); err != nil && !os.IsNotExist(err) {
				return fmt.Errorf("remove stale tools fragment: %w", err)
			}
		}
		return nil
	}
	cfg := GenerateTools(s.Plan.Tools.Versions)
	if err := writeConfig(s.ConfigPath, cfg); err != nil {
		return fmt.Errorf("write tools mise config: %w", err)
	}
	if err := s.Runner.EnsureAndInstall(ctx, s.ConfigPath); err != nil {
		return fmt.Errorf("mise install: %w", err)
	}
	if s.FragmentPath != "" {
		fragment := "# Generated by dotdrift — do not edit.\n" + cfg
		if err := writeConfig(s.FragmentPath, fragment); err != nil {
			return fmt.Errorf("write tools activation fragment: %w", err)
		}
	}
	return nil
}

// DotfilesStep runs mise dotfiles apply for the dotfiles in the resolved plan.
type DotfilesStep struct {
	Runner     Runner
	Plan       *resolve.Plan
	ConfigPath string
	Yes        bool
	// Force maps to dotdrift apply --force (issue 0046): replace pre-existing
	// regular files at managed targets (e.g. an app-written file where a
	// symlink should go) instead of aborting with mise's "refusing to
	// overwrite existing files". Default off — refusal is the safety;
	// onboard is the deliberate takeover path.
	Force bool
}

var _ apply.Step = (*DotfilesStep)(nil)

func (s *DotfilesStep) Name() string { return "dotfiles" }

func (s *DotfilesStep) Run(ctx context.Context) error {
	if s.Runner == nil {
		return fmt.Errorf("no mise runner configured")
	}
	if s.Plan == nil {
		return fmt.Errorf("plan is nil")
	}
	if len(s.Plan.Dotfiles.Entries) == 0 {
		return nil
	}
	cfg := GenerateDotfiles(s.Plan.Dotfiles.Entries)
	if err := writeConfig(s.ConfigPath, cfg); err != nil {
		return fmt.Errorf("write dotfiles mise config: %w", err)
	}
	// Force comes from dotdrift apply --force (issue 0046). Default off:
	// apply must refuse to clobber pre-existing files it does not own (mise
	// errors naming them; onboard is the takeover path).
	if err := s.Runner.DotfilesApply(ctx, s.ConfigPath, s.Yes, s.Force); err != nil {
		return fmt.Errorf("mise dotfiles apply: %w", err)
	}
	return nil
}

// HooksStep runs each pre/post hook command as its own mise task from the
// generated apply config. Per-command execution preserves hook order while
// allowing individual hooks to opt out of fail-fast: a command marked
// Optional that exits non-zero is logged at warn and the next command runs.
// cmd/apply.go only constructs HooksSteps for non-empty command lists; Run
// also no-ops on an empty list as a second line of defense.
//
// Each command maps to a mise task named <Task>-<index> (e.g. hooks-pre-0),
// which GenerateHookTasks emits in lockstep with this loop.
type HooksStep struct {
	Exec       *ExecMise
	Commands   []profile.HookCommand
	ConfigPath string
	Task       string // mise task-name prefix, e.g. "hooks-pre"; per-command tasks are <Task>-<i>
	StepName   string // pipeline step name, e.g. "hooks-pre"
	// Interactive mirrors the interactive = true opt-in written into the
	// tasks at config-write (0064-D4): interactive commands must reach the
	// real terminal, so with a Handover callback every task runs through it
	// (issue 0071) instead of the piped runner.
	Interactive bool
	// Handover runs one child command on the consumer's terminal. Injected
	// by the apply session; nil (no session) keeps the piped runner path.
	Handover apply.HandoverFunc

	obs apply.Observer // injected by the pipeline; nil = no observation
}

var (
	_ apply.Step         = (*HooksStep)(nil)
	_ apply.HandoverStep = (*HooksStep)(nil)
)

func (s *HooksStep) Name() string { return s.StepName }

// RequiresTTY classifies the step up front (0064-D4): interactive hook
// commands run on the consumer's terminal.
func (s *HooksStep) RequiresTTY() string {
	if s.Interactive && len(s.Commands) > 0 {
		return "interactive hook commands run on your terminal"
	}
	return ""
}

// SetHandover injects the consumer's handover callback (apply.HandoverStep).
func (s *HooksStep) SetHandover(h apply.HandoverFunc) { s.Handover = h }

// SetObserver receives the pipeline observer (apply.observerSetter) so the
// step can announce per-command hook boundaries (issue 0071).
func (s *HooksStep) SetObserver(o apply.Observer) { s.obs = o }

func (s *HooksStep) Run(ctx context.Context) error {
	if len(s.Commands) == 0 {
		return nil
	}
	if s.Exec == nil {
		return fmt.Errorf("no mise exec configured")
	}
	for i, c := range s.Commands {
		task := fmt.Sprintf("%s-%d", s.Task, i)
		sub := apply.SubStep{Index: i, Total: len(s.Commands), Command: c.Command}
		if s.obs != nil {
			s.obs.HookStarted(s.StepName, sub)
		}
		var err error
		if s.Interactive && s.Handover != nil {
			var cmd *exec.Cmd
			cmd, err = s.Exec.RunTaskSpec(ctx, s.ConfigPath, task)
			if err == nil {
				err = s.Handover(cmd)
			}
		} else {
			err = s.Exec.RunTask(ctx, s.ConfigPath, task)
		}
		if err != nil {
			if s.obs != nil {
				s.obs.HookFailed(s.StepName, sub, err)
			}
			if c.Optional {
				log.Warn().Err(err).Str("command", c.Command).Msg("optional hook failed; continuing")
				continue
			}
			return fmt.Errorf("hook %q: %w", c.Command, err)
		}
	}
	return nil
}

func writeConfig(path, content string) error {
	if path == "" {
		return fmt.Errorf("config path is empty")
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}
