id = "nvim"
app = "nvim"

[packages]
present = ["neovim"]

[tools]
node = "20"

[dotfiles]
"~/.config/nvim/init.lua" = { source = "config/init.lua", mode = "symlink" }
"~/.config/nvim/lua/options.lua" = { source = "config/lua/options.lua", mode = "symlink" }
